from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

styles = getSampleStyleSheet()


def generate_pdf(profile, repos, ai_analysis):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    elements = []

    # ----------------------------
    # Title
    # ----------------------------

    title = styles["Title"]
    title.alignment = TA_CENTER

    elements.append(
        Paragraph(
            "AI GitHub Developer Analysis Report",
            title,
        )
    )

    elements.append(Spacer(1, 20))

    

    # ----------------------------
    # Candidate Information
    # ----------------------------

    heading = styles["Heading2"]

    elements.append(Paragraph("Candidate Information", heading))

    profile_table = Table([
        ["Name", profile.get("name", "N/A")],
        ["Username", profile.get("login", "N/A")],
        ["Company", profile.get("company") or "N/A"],
        ["Location", profile.get("location") or "N/A"],
        ["Followers", str(profile.get("followers", 0))],
        ["Repositories", str(profile.get("public_repos", 0))],
       
    ])


    profile_table.setStyle(
        TableStyle([
             ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

        ("ALIGN", (2, 1), (2, -1), "CENTER")
        ])
    )

    elements.append(profile_table)

    elements.append(Spacer(1, 20))

    # ----------------------------
    # AI Analysis
    # ----------------------------

    elements.append(
        Paragraph(
            "AI Developer Assessment",
            heading,
        )
    )

    ai_text = ai_analysis.replace("\n", "<br/>")

    elements.append(
        Paragraph(
            ai_text,
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 20))

    # ----------------------------
    # Footer
    # ----------------------------

    footer = Paragraph(
        "<b>Generated by AI GitHub Developer Analyzer | Author - Murari Shrivastava</b>",
        styles["Italic"],
    )

    elements.append(footer)

    doc.build(elements)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf